export const INVITATION_CONSTRAINTS = {
    // INVITATION MESSAGE CONSTRAINTS
    MESSAGE_MAX_LENGTH: 250,
    MESSAGE_REGEX_FORMAT: /^[^<>]*$/s,
    
    // STATUS CONSTRAINTS
    STATUS_ALLOWED_OPTIONS: {
        PENDING: 'PENDING',
        ACCEPTED: 'ACCEPTED',
        REJECTED: 'REJECTED',
        EXPIRED: 'EXPIRED'
    }
} as const

export const ALLOWED_INVITATION_STATUS = Object.values(INVITATION_CONSTRAINTS.STATUS_ALLOWED_OPTIONS)
export type InvitationStatusOptions = typeof INVITATION_CONSTRAINTS.STATUS_ALLOWED_OPTIONS[keyof typeof INVITATION_CONSTRAINTS.STATUS_ALLOWED_OPTIONS]