export const MEMBER_CONSTRAINTS = {
    // ROLE CONSTRAINTS
    ROLE_ALLOWED_OPTIONS: {
        ADMIN: 'ADMIN',
        CONTRIBUTOR: 'CONTRIBUTOR'
    },

    // STATUS CONSTRAINTS
    STATUS_ALLOWED_OPTIONS: {
        ACTIVE: 'ACTIVE',
        INACTIVE: 'INACTIVE',
        ON_LEAVE: 'ON_LEAVE'
    }
} as const

export const ALLOWED_MEMBER_ROLES = Object.values(MEMBER_CONSTRAINTS.ROLE_ALLOWED_OPTIONS)
export const ALLOWED_MEMBER_STATUS = Object.values(MEMBER_CONSTRAINTS.STATUS_ALLOWED_OPTIONS)
export type MemberRoleOptions = typeof MEMBER_CONSTRAINTS.ROLE_ALLOWED_OPTIONS[keyof typeof MEMBER_CONSTRAINTS.ROLE_ALLOWED_OPTIONS]
export type MemberStatusOptions = typeof MEMBER_CONSTRAINTS.STATUS_ALLOWED_OPTIONS[keyof typeof MEMBER_CONSTRAINTS.STATUS_ALLOWED_OPTIONS]