export const PROJECT_CONSTRAINTS = {
    // TITLE CONSTRAINTS
    TITLE_MIN_LENGTH: 3,
    TITLE_MAX_LENGTH: 50,
    TITLE_REGEX_FORMAT: /^[a-zA-Z0-9À-ÿ][a-zA-Z0-9À-ÿ\s.\-_]*$/,

    // DESCRIPTION CONSTRAINTS
    DESCRIPTION_MAX_LENGTH: 1000,
    DESCRIPTION_REGEX_FORMAT: /^[^<>]*$/s,

    // CATEGORY CONSTRAINTS
    CATEGORY_MIN_LENGTH: 1,
    CATEGORY_ALLOWED_OPTIONS: {
        DEVELOPMENT_ENGINEERING: 'DEVELOPMENT/ENGINEERING',
        DESIGN_UX: 'DESIGN/UX',
        MAINTENANCE_SUPPORT: 'MAINTENANCE/SUPPORT',
        INFRASTRUCTURE_DEVOPS: 'INFRASTRUCTURE/DEVOPS',
        DATA_ANALYSIS: 'DATA/ANALYSIS',
        MARKETING_SALES: 'MARKETING/SALES'
    },

    // STATUS CONSTRAINTS
    STATUS_MIN_LENGTH: 1,
    STATUS_ALLOWED_OPTIONS: {
        PLANNED: 'PLANNED',
        IN_PROGRESS: 'IN_PROGRESS',
        COMPLETED: 'COMPLETED',
        ARCHIVED: 'ARCHIVED'
    }
} as const

export const ALLOWED_PROJECT_CATEGORIES = Object.values(PROJECT_CONSTRAINTS.CATEGORY_ALLOWED_OPTIONS)
export const ALLOWED_PROJECT_STATUS = Object.values(PROJECT_CONSTRAINTS.STATUS_ALLOWED_OPTIONS)
export type ProjectStatusOptions = typeof PROJECT_CONSTRAINTS.STATUS_ALLOWED_OPTIONS[keyof typeof PROJECT_CONSTRAINTS.STATUS_ALLOWED_OPTIONS]
export type ProjectCategoryOptions = typeof PROJECT_CONSTRAINTS.CATEGORY_ALLOWED_OPTIONS[keyof typeof PROJECT_CONSTRAINTS.CATEGORY_ALLOWED_OPTIONS]