export const TASK_CONSTRAINTS = {
    // DESCRIPTION CONSTRAINTS
    DESCRIPTION_MIN_LENGTH: 10,
    DESCRIPTION_MAX_LENGTH: 3000,
    DESCRIPTION_REGEX_FORMAT: /^[^<>]*$/s,

    // OBJECTIVE CONSTRAINTS
    OBJECTIVE_MIN_LENGTH: 3,
    OBJECTIVE_MAX_LENGTH: 70,
    OBJECTIVE_REGEX_FORMAT: /^[a-zA-Z0-9À-ÿ][a-zA-Z0-9À-ÿ\s.\-_]*$/,

    // PRIORITY CONSTRAINTS
    PRIORITY_ALLOWED_OPTIONS: {
        LOW: 'LOW',
        MEDIUM: 'MEDIUM',
        HIGH: 'HIGH',
        CRITICAL: 'CRITICAL'
    },

    // STATUS CONSTRAINTS
    STATUS_ALLOWED_OPTIONS: {
        TODO: 'TODO',
        DOING: 'DOING',
        REVIEW: 'REVIEW',
        COMPLETED: 'COMPLETED',
        OVERDUE: 'OVERDUE'
    }
} as const

export const ALLOWED_PRIORITY_OPTIONS = Object.values(TASK_CONSTRAINTS.PRIORITY_ALLOWED_OPTIONS)
export const ALLOWED_STATUS_OPTIONS = Object.values(TASK_CONSTRAINTS.STATUS_ALLOWED_OPTIONS)

export type TaskPriorityOptions = typeof TASK_CONSTRAINTS.PRIORITY_ALLOWED_OPTIONS[keyof typeof TASK_CONSTRAINTS.PRIORITY_ALLOWED_OPTIONS]
export type TaskStatusOptions = typeof TASK_CONSTRAINTS.STATUS_ALLOWED_OPTIONS[keyof typeof TASK_CONSTRAINTS.STATUS_ALLOWED_OPTIONS]