export const USER_CONSTRAINTS = {
    // EMAIL CONSTRAINTS
    EMAIL_MAX_LENGTH: 254,
    EMAIL_REGEX_FORMAT: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,

    // LASTNAME CONSTRAINTS
    LASTNAME_MIN_LENGTH: 2,
    LASTNAME_MAX_LENGTH: 50,
    LASTNAME_REGEX_FORMAT: /^[a-zA-ZÀ-ÿ\s'-]+$/,

    // NAME CONSTRAINTS
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 20,
    NAME_REGEX_FORMAT: /^[a-zA-ZÀ-ÿ\s'-]+$/,

    // PASSWORD CONSTRAINTS
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 100,
    PASSWORD_REGEX_FORMAT: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/,
    
    // STATUS CONSTRAINTS
    STATUS_MIN_LENGTH: 1,
    STATUS_ALLOWED_OPTIONS: {
        ACTIVE: 'ACTIVE',
        SUSPENDED: 'SUSPENDED',
        PENDING_VERIFICATION: 'PENDING_VERIFICATION'
    },
    
    // USERNAME CONSTRAINTS
    USERNAME_MIN_LENGTH: 3,
    USERNAME_MAX_LENGTH: 30,
    USERNAME_REGEX_FORMAT: /^[a-zA-Z0-9._-]+$/
} as const

export const ALLOWED_USER_STATUS = Object.values(USER_CONSTRAINTS.STATUS_ALLOWED_OPTIONS)
export type UserStatusOptions = typeof USER_CONSTRAINTS.STATUS_ALLOWED_OPTIONS[keyof typeof USER_CONSTRAINTS.STATUS_ALLOWED_OPTIONS]