export const MemberErrorCodes = {
    //DOMAIN ERRORS
    MEMBER_NOT_FOUND: 'MBR_ERROR_001',
    MEMBER_ALREADY_EXISTS: 'MBR_ERROR_002',
    MEMBER_VALIDATION_FAILED: 'MBR_ERROR_003',

    //ENTITY BUSINESS RULES
    MEMBER_LINK_INMUTABLE: 'MBR_ERROR_004',
    MEMBER_NOT_ACTIVE: 'MBR_ERROR_005',
    MEMBER_NOT_PERMITTED_CHGROLE: 'MBR_ERROR_006',
    MEMBER_NOT_PERMITTED_CHGSTS: 'MBR_ERROR_007',
    MEMBER_ACTIVE_TASKS_REMOVAL: 'MBR_ERROR_008',
    MEMBER_ACTIVE_TASKS_INACTIVATE: 'MBR_ERROR_009',
    MEMBER_ACTIVE_TASKS_ON_LEAVE: 'MBR_ERROR_012',
    MEMBER_VERIFICATION_PENDING: 'MBR_ERROR_010',
    MEMBER_USER_NOT_ELIGIBLE: 'MBR_ERROR_011',
    MEMBER_OWNER_ROLE_LOCKED: 'MBR_ERROR_013',
    MEMBER_NOT_PERMITTED_TO_CREATE: 'MBR_ERROR_014'
} as const

export type MemberErrorCode = typeof MemberErrorCodes[keyof typeof MemberErrorCodes]
export type MemberErrorKeys = keyof typeof MemberErrorCodes