
export const ProjectErrorCodes = {
    //DOMAIN ERRORS
    PROJECT_NOT_FOUND: 'PRJ_ERR_001',
    PROJECT_ALREADY_EXISTS: 'PRJ_ERR_002',
    PROJECT_VALIDATION_FAILED: 'PRJ_ERR_003',

    //ENTITY BUSINESS RULES
    PROJECT_CATEGORY_INMUTABLE: 'PRJ_ERR_004',
    PROJECT_COMPLETED_LOCKED: 'PRJ_ERR_005',
    PROJECT_COMPLETION_PENDING_TASKS: 'PRJ_ERR_006',
    PROJECT_ARCHIVED_LOCKED: 'PRJ_ERR_007',
    PROJECT_NOBACKUP_ADMIN: 'PRJ_ERR_008',
    PROJECT_OWNER_INMUTABLE: 'PRJ_ERR_009',
    PROJECT_ARCHIVE_INCONSISTENCY: 'PRJ_ERR_010',
    PROJECT_NOT_OWNER: 'PRJ_ERR_011',
    PROJECT_NOT_OWNER_OR_ADMIN: 'PRJ_ERR_012',
    PROJECT_TASKS_REQUIRED: 'PRJ_ERR_013',
    PROJECT_INVALID_TRANSITION: 'PRJ_ERR_014',
    PROJECT_MEMBERS_REQUIRED: 'PRJ_ERR_015',
    PROJECT_NOT_MEMBER_ERROR: 'PRJ_ERR_017',
    PROJECT_MEMBER_WIP_LIMIT_REACHED: 'PRJ_ERR_018',
    PROJECT_NOBACKUP_CONTRIBUTORS: 'PRJ_ERR_019',

} as const

export type ProjectErrorCode = typeof ProjectErrorCodes[keyof typeof ProjectErrorCodes]