export const TaskErrorCodes = {
    // DOMAIN ERRORS
    TASK_NOT_FOUND: 'TSK_ERROR_001',
    TASK_ALREADY_EXISTS: 'TSK_ERROR_002',
    TASK_VALIDATION_FAILED: 'TSK_ERROR_003',

    //ENTITY BUSINESS RULES
    TASK_CREATOR_REQUIRED: 'TSK_ERROR_004',
    TASK_DUEDATE_INCONSISTENCY: 'TSK_ERROR_005',
    TASK_DOING_PENDING_ASSIGNEDTO: 'TSK_ERROR_006',
    TASK_COMPLETED_LOCKED: 'TSK_ERROR_007',
    TASK_USER_NOT_PERMITTED_TOEDIT: 'TSK_ERROR_008',
    TASK_USER_NOT_PERMITTED_TOEXTEND: 'TSK_ERROR_009',
    TASK_PROJECT_INMUTABLE: 'TSK_ERROR_010',
    TASK_OVERDUE_LOCKED: 'TSK_ERROR_011',
    TASK_INVALID_TRANSITION: 'TSK_ERR_012',
    TASK_REVIEW_LOCKED: 'TSK_ERR_013',
    TASK_ASSIGNMENT_MISMATCH: 'TSK_ERR_14'
} as const

export type TaskErrorCode = typeof TaskErrorCodes[keyof typeof TaskErrorCodes]