export const UserErrorCodes = {
    //DOMAIN ERRORS
    USER_NOT_FOUND: 'USER_ERROR_001',
    USER_USERNAME_ALREADY_EXISTS: 'USER_ERROR_002',
    USER_EMAIL_ALREADY_EXISTS: 'USER_ERROR_010',
    USER_VALIDATION_FAILED: 'USER_ERROR_003',

    //ENTITY BUSINESS RULES
    USER_NOT_VERIFIED: 'USER_ERROR_004',
    USER_USERNAME_CHANGE_LIMIT: 'USER_ERROR_005',
    USER_EMAIL_REVERIFICATION_REQUIRED: 'USER_ERROR_006',
    USER_SUSPENDED_LOCKED: 'USER_ERROR_007',
    USER_NOT_ACTIVE_FOR_ACTION: 'USER_ERROR_008',
    USER_MAX_ADMIN_ROLES_REACHED: 'USER_ERROR_009',
    USER_ALREADY_ACTIVE: 'USER_ERROR_011',
    USER_PASSWORD_REUSE: 'USER_ERROR_012'
} as const

export type UserErrorCode = typeof UserErrorCodes[keyof typeof UserErrorCodes]
export type UserErrorKeys = keyof typeof UserErrorCodes