name: Synergy CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Lint, Typecheck & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node JS
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm run server:prisma-generate

      - name: Typecheck
        run: pnpm run typecheck:build

      - name: Build monorepo packages
        run: pnpm run build:all

  testing:
    name: Run Automated Tests
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node JS
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm run server:prisma-generate

      - name: Unit tests
        run: pnpm run test:unit

      - name: Integration tests
        run: pnpm run test:integration

  snyk:
    name: Security Analisis (SCA, SAST & Secret Scan)
    needs: testing
    permissions:
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run Snyk Code & Open Source Scan to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        with:
          args: --monitor --all-projects --severity-threshold=high --sarif-file-output=snyk.sarif

      - name: Upload result to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  docker:
    name: Docker Build, Verify & Container Security Scan
    needs: snyk
    permissions: 
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: synergy-server:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: "synergy-server:test"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Generate Trivy SARIF report
        if: always()
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: "synergy-server:test"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
